version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  queue-worker:
    build:
      context: ./docker/php
    container_name: queue-worker
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: php artisan queue:work --tries=1
    depends_on:
      - redis
      - postgres

volumes:
  pgdata:
